language: node_js
node_js:
  - 8
install:
  - npm install -g codecov
cache: yarn
before_script:
  - yarn
script:
  - yarn test
  - yarn build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
os:
  - linux
