export const BaseTypes = [
    'OpenQuestion',
    'CloseQuestion',
    'MatrixSingleQuestion',
    'OrderQuestion',
    'DivideQuestion',
    'MediaQuestion',
];

export const QuestionTypes = {
    OpenQuestion: 'Otevřená',
    CloseQuestion: 'Uzavřená',
    CloseWithOpenQuestion: 'Uzavřená s vlasní odpovědí',
    CloseMultiQuestion: 'Uzavřená s více možnostmi',
    CloseMultiWithOpenQuestion: 'Zavřená s více možnostmi a vlastní odpovědí',
    MatrixSingleQuestion: 'Maticová otázka',
    MatrixMultiQuestion: 'Maticová otázka s volbou více možností',
    MatrixTextQuestion: 'Maticová s texte',
    OrderQuestion: 'Seřazovací otázka',
    DivideQuestion: 'Rozdělovací otázka',
    OpenLongQuestion: 'Open long',
    OpenWithImageQuestion: 'Otevřená s obrázkem v zadání',
    MediaQuestion: 'Uzavřená s obrázkem v zadání',
    MediaMultiQuestion: 'Uzavřená s více možnostmi s obrázkem v zadání',
    MediaWithOpenQuestion: 'Uzavřená s obrázkem a vlastní odpovědí',
    MediaMultiWithOpenQuestion: 'Uzavřená s více možnostmi s obrázkem a vlastní odpovědí',
    ImageOptionsQuestion: 'Obrázky jako možnosti',
    ImageOptionsMultiQuestion: 'Obrázky jako možnosti multiple choice',
    ImageOptionsWithOpenQuestion: 'Obrázky jako možnosti s vlastní odpovědí',
    ImageOptionsMultiWithOpenQuestion: 'Obrázky jako možnosti s vlastní odpovědí multiple',
    MatrixSingleImageQuestion: 'Maticová s obrázky',
    MatrixMultiImageQuestion: 'Maticová s obrázky multiple',
    OpenWithImageQuestionLong: 'Open long s obrazkem v zadani',
};
